name: Check translations

on:
  push:
    paths:
    - 'locales/*.po'
  pull_request:
    paths:
    - 'locales/*.po'

jobs:
  check-po-validity:
    name: Check translations
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GNU gettext
      run: sudo apt-get install gettext

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        cache-dependency-glob: "scripts/check-translations.py"

    - name: Check translations
      run: uv run scripts/check-translations.py --github
